### ISSUE TITLE
Add sorting for contacts list (or sort by last name as default)

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#51]
It would be nice to be able to sort our list of contacts by last name. I would accept if that were the default (rather than "set at the top" which I think is what it is now?) if a sorting UI is too complicated at his stage.

**Comment by jakelowen** [comment]
I can default to sorting by last name, absolutely.  A future UI to allow custom sorting is possible, but those would need to refetch the data from the server in the specified sort order (as opposed to a simple front end sorting) because list members are "lazy-loaded" and are fetched in batches. 

But for now I will default to last name sort.

**Comment by jakelowen** [comment]
Well, that was easy enough:

```
<Mutation
        mutation={NEW_POTENTIAL_VOTER}
        update={(store, { data: { createPotentialVoter } }) => {
          const data = store.readQuery({
            query: MY_POTENTIAL_VOTERS,
            variables: { limit: 25, org_id: this.props.match.params.orgSlug },
          });
          // Push item to top of the list
          data.potentialVoters.items.push(createPotentialVoter);
          data.potentialVoters.items = sortBy(data.potentialVoters.items, ['last_name']);
          store.writeQuery({
            query: MY_POTENTIAL_VOTERS,
            variables: { org_id: this.props.match.params.orgSlug, limit: 25 },
            data,
          });
        }}
      >
```

**Comment by MainStreamDanny** [comment]
Snort! I just stayed away and you iterated through and fixed it! Yay!
