### ISSUE TITLE
Add "Voter?" (or "Reg?") and TODO to non-matched contacts

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/relational_gotv#61]
When a contact is entered but not matched, they should still have the "Voter? No" button (or "Reg? No" button see #60 ), and they should have a TODO task to either match the contact to the voter list, or get them registered to vote.

When they click on "Voter? No" it should pop up like it does when they are matched, but say something about how they may need to be matched (with a link to the match routine) or they may not be in the voter list yet, or they may need to register to vote (with a link to that task).

When they click on "TODO" they should get task to either match the contact or get them to register to vote.

**Comment by jakelowen** [comment]
I can do this.. but I'm reluctant for only one reason.  As it stands now the only way to complete a task is to actually use the interface to complete the task.  If we implement your suggestion and have a "match to voter file" as an initial default task, then one of two things must happen:

1. The user will not be able to manually complete the task via the task interface. They will have to complete the voter match process which will in turn dispatch the necessary background operations to mark an outstanding "registration task" as complete.  
 - OR -
2. The user can manually complete the voter reg task via the task interface but then what happens if they did not actually complete the matching? The task interface would require a pretty big refactor to provide for this kind of externally validated pre-requisite to completion.

I actually thought about this UI choice quite a bit. In my mind the way it is now makes most sense.  After a new contact is added, the very first most important thing is to match them to the file. Before that happens they aren't fully "in the system".  So on initial add, we only allow one option - to match the voter.

I'm open to discussing, but if we want to make this change we need to think through a few things...

**Comment by jakelowen** [comment]
OK.. I think this makes sense now.  I think I will approach this as if "task zero" is a hardcoded pseudo-task.  For the user it will appear to be a normal task, but it won't actually exist as a row in the task table of the database.  Basically if the voter is matched, then show a real task. If not, show task 0.

**Comment by MainStreamDanny** [comment]
Yes, that works for me. However you need it to happen works for me.

**Comment by jakelowen** [comment]
Adding from Danny email:

Huh. Okay, here was my thought:

Unmatched contacts have the following choices:

Tasks 5/5    (button, 5 left of 5 total)
Registered? No     (status/button)

If they hit the Tasks button, they will be presented with Task zero: "Match this person to the voter file.” It will have a link to the matchmaking routine, as well as explanatory text on what this does, ala: “Your first task is to make sure this person is registered to vote! First, check to see if you can match them up with a record in the public voter file provided by your county. (Click here to search for a match) If they aren’t there, it might be that they aren’t registered to vote. You should contact them and ask them if they’ve registered recently, or if you might have their name or city wrong. If they aren’t registered, or they don’t know, encourage them to go to ksvotes.org to check their registration or to register.”

If they hit the Registered? No button, they get a status report of the registration status, like they would if it was “Registered? Yes” but it says they have not been matched to a voter file, and has a link that directs them to task zero.

How does that sound?
